# Site settings
title: Chase Î»
email: t.heicfire@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.chaselambda.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  theicfire

# Build settings
markdown: kramdown
kramdown:
    input: GFM
syntax-highlighting:
    enabled: true
    css: syntax.css
highlighter: pygments
